name: git_commit_streak
description: A tool that shows the number of consecutive days with at least one
  commit per day.
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  cron: ^0.5.1
  cupertino_icons: ^1.0.5
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_hooks: ^0.18.5+1
  flutter_local_notifications: ^13.0.0
  flutter_markdown: ^0.6.14
  hooks_riverpod: ^2.1.3
  intl: ^0.18.0
  macos_ui: ^1.11.1
  mixin_logger: ^0.0.3
  path: ^1.8.2
  pubspec_parse: ^1.2.1
  shared_preferences: ^2.0.17

dev_dependencies:
  custom_lint: ^0.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.1.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - pubspec.yaml
